name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [ main ]
  # Run hourly between 8am and 10pm GMT/UTC
  schedule:
    - cron: '0 8-22 * * *'  # 8am-10pm GMT/UTC
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:22
      # Required for Puppeteer to run in container
      options: --security-opt seccomp=unconfined
    environment: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9.15.4'
          run_install: false

      # Install system dependencies for Puppeteer
      - name: Install Puppeteer dependencies
        run: |
          apt-get update
          apt-get install -y chromium chromium-sandbox ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

      - name: Install dependencies
        run: pnpm install

      - name: Create data directory
        run: mkdir -p src/data

      - name: Fetch standings Excel file
        run: pnpm run fetch-standings-excel-file

      - name: Generate standings JSON
        run: pnpm run generate-standings-json

      - name: Fetch iRacing data
        run: pnpm run fetch-iracing-data-ci
        env:
          EMAIL: ${{ vars.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Build site
        run: pnpm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4